// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NaukriUpdate.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NaukriLoginAndUpdate")]
    public partial class NaukriLoginAndUpdateFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "NaukriLoginAndUpdate.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "NaukriLoginAndUpdate", "I should be able to update user  profile page", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify User can update Resume Heading details in naukri profile")]
        [NUnit.Framework.TestCaseAttribute("archana.bangar2018@gmail.com", "123Shubh#", "Java, C# Selenium Webdriver Automation Tester,Functional-Web Service Testing,Spec" +
            "Flow,Accessibility Testing,API Testing,SQL,BDD,KDF,Cucumber,RESTAssure,Agile Scr" +
            "um,Functional Testing,People Mangmnt,Defect tracking, JIRA,TestNG,HPALM,JUnit.", null)]
        [NUnit.Framework.TestCaseAttribute("archana.bangar2018@gmail.com", "123Shubh#", "Java, C# Selenium Webdriver Automation Tester,Functional-Web Service Testing,Spec" +
            "Flow,Accessibility Testing,API Testing,SQL,BDD,KDF,Cucumber,RESTAssure,Agile Scr" +
            "um,Functional Testing,People Mangmnt,Defect tracking, JIRA,TestNG,HPALM,JUnit..", null)]
        [NUnit.Framework.TestCaseAttribute("archana.bangar2018@gmail.com", "123Shubh#", "Java, C# Selenium Webdriver Automation Tester,Functional-Web Service Testing,Spec" +
            "Flow,Accessibility Testing,API Testing,SQL,BDD,KDF,Cucumber,RESTAssure,Agile Scr" +
            "um,Functional Testing,People Mangmnt,Defect tracking, JIRA,TestNG,HPALM,JUnit..." +
            "", null)]
        [NUnit.Framework.TestCaseAttribute("shubhamgagile@gmail.com", "123Shubh@", "14 yrs in Agile Program and Delivery,People Management,stakeholder management,Del" +
            "ivery Management, key metrics, budget,Risk, communication management, Delivery L" +
            "eadership,Escalation Managmnt,Quality Management,CSM,PMP,PRINCE2certified", null)]
        [NUnit.Framework.TestCaseAttribute("shubhamgagile@gmail.com", "123Shubh@", "14 yrs in Agile Program and Delivery,People Management,stakeholder management,Del" +
            "ivery Management, key metrics, budget,Risk, communication management, Delivery L" +
            "eadership,Escalation Managmnt,Quality Management,CSM,PMP,PRINCE2certified.", null)]
        [NUnit.Framework.TestCaseAttribute("shubhamgagile@gmail.com", "123Shubh@", "14 yrs in Agile Program and Delivery,People Management,stakeholder management,Del" +
            "ivery Management, key metrics, budget,Risk, communication management, Delivery L" +
            "eadership,Escalation Managmnt,Quality Management,CSM,PMP,PRINCE2certified..", null)]
        public void VerifyUserCanUpdateResumeHeadingDetailsInNaukriProfile(string userName, string password, string resumeHeadline, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("ResumeHeadline", resumeHeadline);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify User can update Resume Heading details in naukri profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
testRunner.Given("I launch Naukri portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
testRunner.And(string.Format("I login using {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 8
testRunner.When("I click on profile link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
testRunner.And("I click on Resume Headline Edit Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
testRunner.And(string.Format("I enter ResumeHeadline as {0}", resumeHeadline), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
testRunner.And("I click on Resume Headline Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
testRunner.Then(string.Format("I Verify Resume Headline Updated Successfully with headline as {0}", resumeHeadline), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
testRunner.And("I close the browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify User can update User Name details in naukri profile")]
        [NUnit.Framework.TestCaseAttribute("archana.bangar2018@gmail.com", "123Shubh#", "Archana B Short Notice Period.", null)]
        [NUnit.Framework.TestCaseAttribute("archana.bangar2018@gmail.com", "123Shubh#", "Archana Bangar Short Notice.", null)]
        [NUnit.Framework.TestCaseAttribute("archana.bangar2018@gmail.com", "123Shubh#", "Archana B Avbl on Short Notice.", null)]
        [NUnit.Framework.TestCaseAttribute("shubhamgagile@gmail.com", "123Shubh@", "Shubham Guptaa", null)]
        [NUnit.Framework.TestCaseAttribute("shubhamgagile@gmail.com", "123Shubh@", "Shubham Gupta", null)]
        public void VerifyUserCanUpdateUserNameDetailsInNaukriProfile(string userName, string password, string fullName, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("FullName", fullName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify User can update User Name details in naukri profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
testRunner.Given("I launch Naukri portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
testRunner.And(string.Format("I login using {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
testRunner.When("I click on profile link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
testRunner.And("I click on Basic Detals Edit Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
testRunner.And(string.Format("I update FullName as {0}", fullName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
testRunner.And("I click on save Basic Details Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
testRunner.Then(string.Format("I should see updated name in Full name as {0}", fullName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
testRunner.And("I close the browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
